'use strict';
const $=s=>document.querySelector(s), app=$('#app');let db,units=[],progress={},settings={xp:0,streak:0,lastDay:null},session=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA');const plusDays=n=>{let d=new Date();d.setDate(d.getDate()+n);return d.toLocaleDateString('en-CA')};
const norm=s=>s.toLocaleLowerCase('de').trim().replace(/[.!?]/g,'').replace(/\s+/g,' ').replace(/^to /,'');
const all=()=>units.flatMap(u=>u.words.map(w=>({...w,unit:u.id,unitTitle:u.title})));const byId=id=>all().find(w=>w.id===id);
function openDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open('julias-english-quest',1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore('data')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function get(key){return new Promise((resolve,reject)=>{let r=db.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function put(key,value){return new Promise((resolve,reject)=>{let t=db.transaction('data','readwrite');t.objectStore('data').put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function save(){await Promise.all([put('units',units),put('progress',progress),put('settings',settings)])}
function initUnits(raw){return raw.map(u=>({id:u.id,title:u.title,words:u.words.map((w,i)=>Array.isArray(w)?{id:u.id+'-'+String(i+1).padStart(3,'0'),en:w[0],de:w[1],example:''}:{id:w.id||u.id+'-'+String(i+1).padStart(3,'0'),en:w.en,de:w.de,example:w.example||''})}))}
function stat(id){return progress[id]||{stage:0,correct:0,wrong:0,due:today(),last:null}};
function progressUpdate(id,ok,write){let s={...stat(id)};if(ok){s.correct++;s.stage=Math.min(5,s.stage+1);s.due=plusDays([0,0,1,3,7,14][s.stage]);settings.xp+=write?20:10}else{s.wrong++;s.stage=Math.max(0,s.stage-1);s.due=today()}s.last=today();progress[id]=s;save()}
function home(){session=null;const a=all(),due=a.filter(w=>stat(w.id).due<=today()),mastered=a.filter(w=>stat(w.id).stage>=5).length,writing=a.filter(w=>stat(w.id).stage>=2).length;app.innerHTML=`<section class="card hero"><h2>Ready for English, Julia? ✨</h2><p class="muted">Dein nächstes Vokabel-Abenteuer wartet!</p><div class="stats"><div class="stat" style="color:#23314c"><strong>${settings.xp}</strong><small>⭐ XP</small></div><div class="stat" style="color:#23314c"><strong>${mastered}/${a.length}</strong><small>🏆 Sicher</small></div><div class="stat" style="color:#23314c"><strong>${due.length}</strong><small>🔁 Fällig</small></div></div></section><section class="card"><h2>Los geht's!</h2><label for="unit">Training</label><select id="unit"><option value="daily">🌟 Tagestraining – alle Units</option>${units.map(u=>`<option value="${esc(u.id)}">${esc(u.title)}</option>`).join('')}</select><label for="direction">Abfragerichtung</label><select id="direction"><option value="de-en">Deutsch → Englisch</option><option value="both">Beide Richtungen</option><option value="en-de">Englisch → Deutsch</option></select><label for="count">Anzahl Wörter</label><select id="count"><option value="10">10 Wörter</option><option value="20">20 Wörter</option><option value="999">Alle verfügbaren</option></select><div class="buttons" style="margin-top:18px"><button id="start">▶ Lernen starten</button><button id="overview" class="secondary">📊 Mein Lernfortschritt</button><button id="manage" class="secondary">⚙️ Units und Backup</button></div></section><section class="card"><h2>Dein Fortschritt</h2><p>${writing} Wörter in der Schreibphase · ${mastered} gemeistert</p><div class="bar"><div class="fill" style="width:${a.length?mastered/a.length*100:0}%"></div></div></section>`;$('#start').onclick=start;$('#overview').onclick=overview;$('#manage').onclick=manage}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function start(){const unit=$('#unit').value,dir=$('#direction').value,n=Number($('#count').value);let a=all().filter(w=>unit==='daily'||w.unit===unit);if(!a.length)return alert('Keine Vokabeln vorhanden');let due=shuffle(a.filter(w=>stat(w.id).due<=today())).sort((a,b)=>(stat(a.id).stage-stat(b.id).stage));let other=shuffle(a.filter(w=>stat(w.id).due>today()));let chosen=[...due,...other].slice(0,n);session={queue:chosen.map(w=>w.id),index:0,dir,review:[],seen:0,correct:0,finished:false};question()}
function question(){if(!session)return;let s=session,w=byId(s.queue[s.index]);if(!w){complete();return}s.current=w.id;s.ask=s.dir==='both'?(s.index%2===0?'de-en':'en-de'):s.dir;s.write=stat(w.id).stage>=2;s.answered=false;const target=s.ask==='de-en'?w.en:w.de.split('|')[0];let choices=shuffle([target,...shuffle(all().filter(x=>x.id!==w.id).map(x=>s.ask==='de-en'?x.en:x.de.split('|')[0]).filter(x=>norm(x)!==norm(target))).filter((v,i,a)=>a.indexOf(v)===i).slice(0,3)]);app.innerHTML=`<section class="card"><div class="flex"><span class="muted small">Frage ${s.index+1} von ${s.queue.length}</span><span class="pill">${s.write?'✍️ Schreiben · 20 XP':'🎯 Multiple Choice · 10 XP'}</span></div><div class="bar" style="margin:16px 0"><div class="fill" style="width:${(s.index+1)/s.queue.length*100}%"></div></div><div class="prompt"><div class="muted small">Übersetze auf ${s.ask==='de-en'?'Englisch':'Deutsch'}</div><strong>${esc(s.ask==='de-en'?w.de.split('|').join(' / '):w.en)}</strong></div>${s.write?`<form id="answerform"><input id="answer" type="text" autocomplete="off" spellcheck="false" placeholder="Deine Übersetzung …" required><button style="margin-top:10px;width:100%">Antwort prüfen</button></form>`:`<div class="answer-grid">${choices.map(c=>`<button class="answer" data-choice="${esc(c)}">${esc(c)}</button>`).join('')}</div>`}<div id="feedback"></div><p class="muted small">${esc(w.unitTitle)}</p></section>`;if(s.write){$('#answerform').onsubmit=e=>{e.preventDefault();check($('#answer').value)}}else document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>check(b.dataset.choice))}
function check(value){let s=session;if(s.answered)return;s.answered=true;let w=byId(s.current);let variants=(s.ask==='de-en'?w.en:w.de).split('|');if(s.ask==='de-en'&&w.en==='there is')variants.push("there's");let ok=variants.some(v=>norm(v)===norm(value));s.seen++;if(ok)s.correct++;else if(!s.review.includes(w.id))s.review.push(w.id);progressUpdate(w.id,ok,s.write);document.querySelectorAll('.answer').forEach(b=>b.disabled=true);let form=$('#answerform');if(form)form.querySelectorAll('input,button').forEach(x=>x.disabled=true);$('#feedback').innerHTML=`<div class="feedback ${ok?'':'bad'}"><strong>${ok?'🌟 Excellent!':'🔁 Das üben wir noch einmal!'}</strong><p>${ok?'Gut gemacht!':'Richtige Antwort: <strong>'+esc(variants.join(' / '))+'</strong>'}</p><button id="next">Weiter →</button></div>`;$('#next').onclick=()=>{s.index++;if(s.index>=s.queue.length){if(s.review.length){s.queue=shuffle(s.review);s.review=[];s.index=0}else{return complete()}}question()}}
function complete(){let s=session;app.innerHTML=`<section class="card" style="text-align:center"><div style="font-size:3rem">🏆</div><h2>Fantastic, Julia!</h2><p><strong>${s.correct} von ${s.seen}</strong> Antworten richtig</p><p>Gesamt: ⭐ ${settings.xp} XP</p><div class="buttons"><button id="again">Noch eine Runde</button><button id="home" class="secondary">Zur Startseite</button></div></section>`;$('#again').onclick=home;$('#home').onclick=home}
function overview(){let a=all();app.innerHTML=`<section class="card"><div class="flex"><h2>📊 Mein Lernfortschritt</h2><button id="back" class="secondary">← Zurück</button></div><p class="muted">🟢 sicher (5) · 🔵 Schreiben (2–4) · ⚪ Multiple Choice (0–1)</p>${units.map(u=>`<h3>${esc(u.title)}</h3>${u.words.map(w=>{let s=stat(w.id);return `<div class="wordrow"><div><strong>${esc(w.en)}</strong><br><small>${esc(w.de.replaceAll('|',' / '))}</small></div><div style="text-align:right"><span class="pill">${s.stage>=5?'🟢':s.stage>=2?'🔵':'⚪'} ${s.stage}/5</span><br><small>Fehler: ${s.wrong}</small></div></div>`}).join('')}`).join('')}</section>`;$('#back').onclick=home}
function manage(){app.innerHTML=`<section class="card"><div class="flex"><h2>⚙️ Units & Backup</h2><button id="back" class="secondary">← Zurück</button></div><p>Deine Units: ${units.map(u=>esc(u.title)+' ('+u.words.length+' Wörter)').join(', ')}</p><h3>Neue Unit importieren</h3><p class="muted small">JSON-Datei mit Unit-ID, Titel und englisch/deutschen Vokabeln. Bereits gelernte Wörter bleiben erhalten.</p><label class="filelabel" for="unitfile">📥 Unit-JSON auswählen</label><input id="unitfile" type="file" accept=".json,application/json"><h3>Gesamten Lernstand sichern</h3><div class="buttons"><button id="export">💾 Backup herunterladen</button><label class="filelabel" for="backupfile">📂 Backup wiederherstellen</label><input id="backupfile" type="file" accept=".json,application/json"></div><p class="muted small">Beim Wiederherstellen werden die aktuellen Daten ersetzt. Erstelle vorher ein Backup.</p><h3>Importformat</h3><p class="muted small">Siehe beiliegende Datei BEISPIEL-UNIT-IMPORT.json.</p></section>`;$('#back').onclick=home;$('#export').onclick=()=>download('julia-english-quest-backup-'+today()+'.json',{format:'julia-english-quest-backup',version:1,units,progress,settings});$('#unitfile').onchange=async e=>{try{let raw=JSON.parse(await e.target.files[0].text());let incoming=initUnits(raw.units||[raw]);for(let u of incoming){let existing=units.find(x=>x.id===u.id);if(existing){let ids=new Set(existing.words.map(w=>w.id));for(let w of u.words){if(!ids.has(w.id))existing.words.push(w)}}else units.push(u)}await save();alert('Unit erfolgreich importiert!');manage()}catch(err){alert('Import fehlgeschlagen: '+err.message)}};$('#backupfile').onchange=async e=>{try{let raw=JSON.parse(await e.target.files[0].text());if(raw.format!=='julia-english-quest-backup'||!Array.isArray(raw.units)||!raw.progress||!raw.settings)throw Error('Ungültiges Backup');if(!confirm('Aktuelle Daten durch das Backup ersetzen?'))return;units=raw.units;progress=raw.progress;settings=raw.settings;await save();alert('Backup wiederhergestellt');home()}catch(err){alert('Wiederherstellung fehlgeschlagen: '+err.message)}}}
function download(name,obj){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
(async()=>{try{db=await openDB();let initial=await (await fetch('words.json')).json();units=await get('units')||initUnits(initial.units);progress=await get('progress')||{};settings=await get('settings')||settings;await save();home();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(()=>{$('#status').textContent='Offline bereit'}).catch(()=>{$('#status').textContent='Offline-Installation prüfen'})}catch(e){app.innerHTML='<section class="card"><h2>Start nicht möglich</h2><p>Bitte die App über localhost oder eine HTTPS-Adresse öffnen. Details: '+esc(e.message)+'</p></section>'}})();
